name: iso_build
on:
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}      
  release:
    runs-on: ubuntu-20.04
    needs: prepare-release    
    strategy:
      matrix:
        ##### EDIT ME #####
        EDITION: [budgie,cinnamon,i3,lxde,lxqt,lxqt-kwin,mate,openbox]
        BRANCH: [stable]
        SCOPE: [minimal,full]
        OFFICE: [true]
        ###################
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - id: image-build
        uses: manjaro/manjaro-iso-action@main
        with:
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: "21.2.5"
          kernel: linux515
          code-name: "Qonos"
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
          office-chooser: ${{ matrix.office }}
          gpg-secret-key-base64: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          cdn77-host: ${{ secrets.CDN_HOST }}
          cdn77-user: ${{ secrets.CDN_USER }}
          cdn77-pwd: ${{ secrets.CDN_PWD }}
      - name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ needs.prepare-release.outputs.release_tag }}
      - name: rollback cdn77 upload
        if: ${{ failure() || cancelled() }}
        run: |
          sshpass -p "${{ secrets.CDN_PWD }}" rsync --delete -vaP --stats \
            -e ssh $(mktemp) ${{ secrets.CDN_USER }}@${{ secrets.CDN_HOST }}:/www/${{ env.edition }}/${{ env.version }}
