name: iso_build
on:
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}      
  release:
    runs-on: ubuntu-20.04
    needs: prepare-release    
    strategy:
      matrix:
        ##### EDIT ME #####
        EDITION: [cinnamon,i3]
        BRANCH: [stable]
        SCOPE: [minimal,full]
        OFFICE: [true]
        ###################
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - id: image-build
        uses: manjaro/manjaro-iso-action@main
        with:
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: "24.0.2"
          kernel: ${{ matrix.kernel }}
          code-name: "Wynsdey"
          office-chooser: "true"
          gpg-secret-key-base64: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          sf-project: manjarolinux
          sf-user: ${{ secrets.SF_USER_NAME }}
          sf-key: ${{ secrets.SF_PRIV_SSHKEY }}
          s3-cfg: ${{ secrets.S3_CFG }}
      - name: rollback sourceforge upload
        if: ${{ failure() || cancelled() }}
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync --delete -vaP --stats \
              -e ssh $(mktemp) ${{ secrets.SF_USER_NAME }}@frs.sourceforge.net:/home/frs/project/${{ env.sf-project }}/${{ env.edition }}/${{ env.version }}
